### ISSUE TITLE
Fix uploading/downloading block diagrams

### ISSUE THREAD

**Issue by cabarnes** [rovercode/rovercode-web#117]
Uploading and downloading block diagram operations are interfacing to the rover API which no longer has the block diagrams. These need to be changed to use the `/api/v1/block-diagrams/` API in the web application.

https://github.com/rovercode/rovercode-web/blob/9dbaf5b9d1af7ba89c3c0c11bb643f93f70532b3/mission_control/static/js/bd-api.js#L112-L149

**Comment by aninternetof** [comment]
This feature was really important when we were hosting mission-control on the rover, because it allowed someone to move a bd from one rover to another. Now that we're hosting it online, I'm starting to question if this feature is needed. If they downloaded it, what could they do except upload it again?

I'm not sure how far you are already toward fixing it, @cabarnes, but should we consider axing this feature instead of fixing it?

**Comment by cabarnes** [comment]
@aninternetof I haven't started at all. I agree that I can't think of a good use of this with it being hosted in the cloud. We should probably just remove the broken feature.
